"""InitDB

Revision ID: 5a91b07ca6c5
Revises: 
Create Date: 2025-10-12 16:22:45.425774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a91b07ca6c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dryers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moonraker_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('moonraker_api_method', sa.String(length=10), nullable=True),
    sa.Column('moonraker_ip', sa.String(length=50), nullable=True),
    sa.Column('moonraker_port', sa.Integer(), nullable=True),
    sa.Column('moonraker_api_key', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('temperature', sa.Integer(), nullable=True),
    sa.Column('max_temperature_delta', sa.Integer(), nullable=True),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.Column('dry_time', sa.Integer(), nullable=True),
    sa.Column('storage_temperature', sa.Integer(), nullable=True),
    sa.Column('humidity_storage_dry_time', sa.Integer(), nullable=True),
    sa.Column('humidity_storage_range', sa.Integer(), nullable=True),
    sa.Column('storage_type', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dryer_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dryer_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=25), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('heater_temperature', sa.Float(), nullable=True),
    sa.Column('heater_is_on', sa.Boolean(), nullable=True),
    sa.Column('heater_fan_is_run', sa.Boolean(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('servo_is_open', sa.Boolean(), nullable=True),
    sa.Column('absolute_humidity', sa.Float(), nullable=True),
    sa.Column('relative_humidity', sa.Float(), nullable=True),
    sa.Column('current_preset_id', sa.Integer(), nullable=True),
    sa.Column('time_left_drying', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dryer_id'], ['dryers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dryer_preset_association',
    sa.Column('dryer_id', sa.Integer(), nullable=False),
    sa.Column('preset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dryer_id'], ['dryers.id'], ),
    sa.ForeignKeyConstraint(['preset_id'], ['presets.id'], ),
    sa.PrimaryKeyConstraint('dryer_id', 'preset_id')
    )
    op.create_table('heater_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('fan_name', sa.String(length=100), nullable=True),
    sa.Column('dryer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dryer_id'], ['dryers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('humidity_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('open_threshold', sa.Float(), nullable=True),
    sa.Column('close_threshold', sa.Float(), nullable=True),
    sa.Column('plateau_duration', sa.Integer(), nullable=True),
    sa.Column('plateau_window_size', sa.Integer(), nullable=True),
    sa.Column('timer_drying_range', sa.Float(), nullable=True),
    sa.Column('dryer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dryer_id'], ['dryers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('led_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('brightness', sa.Integer(), nullable=True),
    sa.Column('dryer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dryer_id'], ['dryers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servo_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('close_angle', sa.Integer(), nullable=True),
    sa.Column('open_angle', sa.Integer(), nullable=True),
    sa.Column('soft_step', sa.Integer(), nullable=True),
    sa.Column('soft_sleep', sa.Float(), nullable=True),
    sa.Column('min_interval', sa.Integer(), nullable=True),
    sa.Column('dryer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dryer_id'], ['dryers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temperature_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_name', sa.String(length=100), nullable=True),
    sa.Column('dryer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dryer_id'], ['dryers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temperature_configs')
    op.drop_table('servo_configs')
    op.drop_table('led_configs')
    op.drop_table('humidity_configs')
    op.drop_table('heater_configs')
    op.drop_table('dryer_preset_association')
    op.drop_table('dryer_logs')
    op.drop_table('presets')
    op.drop_table('moonraker_configs')
    op.drop_table('dryers')
    # ### end Alembic commands ###